import type { Configuration, Periodicity } from "../../src/config";

export default function (): Configuration {
  const frequencies: Periodicity[] = [
    "D",
    "DA",
    "DD",
    "DE",
    "DN",
    "DQ",
    "DT",
    "DV",
    "DW",
    "DX",
    "DZ",
    "J",
    "JD",
    "JH2",
    "JQ",
    "JT",
    "JV",
    "JZ",
    "M",
    "MA",
    "MC",
    "MD",
    "ME",
    "MN",
    "MQ",
    "MS",
    "MT",
    "MV",
    "MX",
    "MZ2",
    "O1",
    //"ondemand",
    "U",
    "UA",
    "UD",
    //"UE",
    "UH",
    //"UN",
    //"UQ",
    //"US",
    "UT",
    "UV",
    "UW",
    //"UX",
    "UZ",
    "W",
    "WA",
    "WD",
    "WE",
    "WN",
    "WP",
    "WQ",
    "WS",
    "WT",
    "WV",
    "WW",
    "WX",
    "WZ",
  ];

  return {
    transactions: frequencies.map((f, idx) => ({
      id: idx + 2,
      drug: {
        drugType: "compoundprescription",
        compoundprescriptionText: `${f}`,
        temporality: "chronic",
        posologyFreeText: `...`,
        periodicity: f,
        // As some values go to 6 years, I have to take one date
        beginmoment: "2015-09-16",
      },
    })),
  };
}
