name: Refresh XML Outputs

on:
  workflow_dispatch:
  push:
    branches: 
      - main
    paths:
      - configurations/**
      - src/**

jobs:
  refreshOutputs:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout code
        uses: actions/checkout@v7
      - uses: actions/setup-node@v7
        name: 📦 Setup Node.js environment
      - name: ☕ Install dependencies
        run: |
          npm install
      - name: 🤖 Generate XML files
        run: |
          npm start
      - name: 🚀 Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          title: Update XML Outputs
          body: |
            This PR update the /output folder files based on /configurations files
